// 补建说明：该文件为后续补建，用于定义终端一致性套件的手工种子 INPUTS（不含 expecteds）；当前进度：首版覆盖 width/wrap/offset 三域种子用例，每个 id 命名其对应的 terminal-contract 条款，expecteds 由 tui-conformance-kit-generate.ts 从引擎生成。
import type {
  LayoutGoldenCase,
  WidthGoldenCase,
} from '../tests/tui/validation-helpers.js'
import type {
  TerminalPrepareOptions,
  TerminalSourceOffsetBias,
} from '../src/public/index.js'

// Width seeds reuse the WidthGoldenCase input shape (id/text/optional widthProfile)
// so expecteds can be generated by computeWidthExpected. Each id names the
// terminal-contract Unicode Width Profile clause it pins.
export type ConformanceWidthInput = Omit<WidthGoldenCase, 'expectedWidth'>

// Wrap seeds reuse the LayoutGoldenCase input shape (id/text/optional prepare/layout)
// so expecteds can be generated by snapshotLayoutCase. Each id names the
// terminal-contract whitespace/break/tab clause it pins.
export type ConformanceWrapInput = Omit<LayoutGoldenCase, 'expected'>

// Offset seeds describe a single source-offset projection request. Each id names the
// terminal-contract Source Mapping And Cursors / Coordinate Projection clause it pins.
export type ConformanceOffsetInput = {
  id: string
  text: string
  prepare?: TerminalPrepareOptions
  columns: number
  startColumn?: number
  sourceOffset: number
  bias?: TerminalSourceOffsetBias
}

const preWrap: TerminalPrepareOptions = { whiteSpace: 'pre-wrap' }

// ~12 width clauses across the default terminal-unicode-narrow@1 profile and one
// explicit ambiguous-wide override.
export const conformanceWidthInputs: readonly ConformanceWidthInput[] = [
  { id: 'width-profile/ascii-printable-narrow', text: 'AB' },
  { id: 'width-profile/cjk-wide', text: '你好' },
  { id: 'width-profile/ambiguous-narrow-default', text: '§±' },
  { id: 'width-profile/ambiguous-narrow-via-override', text: '§±', widthProfile: { ambiguousWidth: 'narrow' } },
  { id: 'width-profile/ambiguous-wide-via-override', text: '§±', widthProfile: { ambiguousWidth: 'wide' } },
  { id: 'width-profile/fullwidth-form', text: 'ＡＢ' },
  { id: 'width-profile/combining-mark-cluster', text: 'éf' },
  { id: 'width-profile/emoji-presentation-wide-default', text: '😀' },
  { id: 'width-profile/emoji-narrow-via-override', text: '😀', widthProfile: { emojiWidth: 'narrow' } },
  { id: 'width-profile/variation-selector', text: '❤️' },
  { id: 'width-profile/zwj-emoji-sequence', text: '\u{1F468}‍\u{1F469}‍\u{1F467}' },
  { id: 'width-profile/regional-indicator-single-default', text: '\u{1F1FA}' },
  { id: 'width-profile/regional-indicator-single-narrow-via-override', text: '\u{1F1FA}', widthProfile: { regionalIndicator: 'flag-pair-wide-single-narrow' } },
  { id: 'width-profile/regional-indicator-pair', text: '\u{1F1EF}\u{1F1F5}' },
  { id: 'width-profile/keycap-sequence', text: '1️⃣' },
  { id: 'width-profile/nbsp-narrow', text: 'a b' },
  { id: 'width-profile/zero-width-space', text: 'a​b' },
  { id: 'width-profile/word-joiner-zero-width', text: 'a⁠b' },
]

// ~14 wrap clauses across whitespace modes, tabs, hard breaks, break opportunities,
// glue, kinsoku, emoji atomicity, single-grapheme overflow, and multi-row source ranges.
export const conformanceWrapInputs: readonly ConformanceWrapInput[] = [
  { id: 'whitespace/normal-collapse-wrap', text: 'alpha beta gamma delta', layout: { columns: 12 } },
  { id: 'whitespace/pre-wrap-preserves-spaces', text: 'a   b   c', prepare: preWrap, layout: { columns: 6 } },
  { id: 'tabs/tab-at-column-zero', text: '\tword', prepare: preWrap, layout: { columns: 12 } },
  { id: 'tabs/tab-with-start-column', text: '\tword', prepare: preWrap, layout: { columns: 12, startColumn: 3 } },
  { id: 'whitespace/lf-empty-rows', text: 'a\n\nb', prepare: preWrap, layout: { columns: 8 } },
  { id: 'whitespace/final-lf-no-extra-row', text: 'abc\n', prepare: preWrap, layout: { columns: 8 } },
  { id: 'break/soft-hyphen-selected-break', text: 'super­califragilistic', layout: { columns: 8 } },
  { id: 'break/zero-width-space-opportunity', text: 'alpha​beta​gamma', layout: { columns: 7 } },
  { id: 'break/word-joiner-no-break-glue', text: 'alpha⁠beta', layout: { columns: 6 } },
  { id: 'break/cjk-kinsoku-wrap', text: '你好世界你好世界', layout: { columns: 6 } },
  { id: 'break/keep-all-word-break', text: '가나다 라마바', prepare: { wordBreak: 'keep-all' }, layout: { columns: 5 } },
  { id: 'break/emoji-cluster-atomicity', text: 'x\u{1F468}‍\u{1F469}‍\u{1F467}y', layout: { columns: 3 } },
  { id: 'break/single-grapheme-overflow', text: '你', layout: { columns: 1 } },
  { id: 'break/cjk-emoji-mixed-wrap', text: '你😀好🙂界', layout: { columns: 4 } },
  { id: 'break/start-column-first-row', text: 'abc def ghi', layout: { columns: 8, startColumn: 5 } },
  { id: 'break/multi-row-source-ranges-paragraph', text: 'one two three four five six', layout: { columns: 9 } },
]

// ~8 offset clauses across exact boundaries, inside-cluster bias, consumed wrap
// delimiters, EOF positions, out-of-range clamp, start column, and CJK.
export const conformanceOffsetInputs: readonly ConformanceOffsetInput[] = [
  { id: 'source-mapping/exact-visible-boundary', text: 'hello world', columns: 16, sourceOffset: 6 },
  { id: 'source-mapping/inside-cluster-bias-before', text: 'éf', columns: 8, sourceOffset: 1, bias: 'before' },
  { id: 'source-mapping/inside-cluster-bias-after', text: 'éf', columns: 8, sourceOffset: 1, bias: 'after' },
  { id: 'source-mapping/consumed-wrap-delimiter-next-row', text: 'aaa bbb', columns: 4, sourceOffset: 4 },
  { id: 'source-mapping/hard-break-next-row', text: 'ab\ncd', prepare: preWrap, columns: 8, sourceOffset: 3 },
  { id: 'source-mapping/eof-ordinary', text: 'hello', columns: 8, sourceOffset: 5 },
  { id: 'source-mapping/eof-after-final-lf', text: 'abc\n', prepare: preWrap, columns: 8, sourceOffset: 4 },
  { id: 'source-mapping/out-of-range-clamp', text: 'hi', columns: 8, sourceOffset: 99 },
  { id: 'source-mapping/start-column-offset', text: 'wrapme here', columns: 8, startColumn: 3, sourceOffset: 7 },
  { id: 'source-mapping/cjk-exact-boundary', text: '你好世界', columns: 8, sourceOffset: 2 },
]
